dist: xenial
language: python
python: "3.6"
env:
  global:
    - COVERALLS_PARALLEL=true
  matrix:
    - KERAS_BACKEND=tensorflow
    - KERAS_BACKEND=tensorflow TF_KERAS=1
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - export LD_LIBRARY_PATH=$HOME/miniconda/envs/test-environment/lib/:$LD_LIBRARY_PATH
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install coveralls
script:
  - ./test.sh
after_success:
  coveralls
notifications:
  webhooks: https://coveralls.io/webhook
